---
language: go

go:
  - tip
  - 1.18
  - 1.17
  - 1.16
  - 1.15
  - 1.14
  - 1.13
  - 1.12
  - 1.11
  - 1.10
  - 1.9
  - 1.8
  - 1.7
  - 1.6
  - 1.5
  - 1.4
  - 1.3

install:
  - make
  - make test
